version: "2"
# Change the ipam (and `ipv4_address`!) as required for your environment
networks:
  webhooks:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

services:
  sd-webhook:
    build: .
    image: sd-webhook
    ports:
      - "8000:80"
    networks:
      webhooks:
        ipv4_address: 172.20.0.2
    # Uncomment the following two lines (and adjust the path) if your handlers
    # are *not* in the rt_handlers directory.
    # volumes:
    #   - ../sd-webhook-handlers:/app/rt_handlers
